version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Moving to project directory...
      - cd Frontend/products   # <--- THIS IS THE FIX
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - ng build --configuration=production
artifacts:
  files:
    - '**/*'
  # This path is relative to where you are after the 'cd' command above
  base-directory: Frontend/products/dist/products/browser